name: Container Build
on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build:
    name: Build and Publish Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GHCR_FULL_NAME: 'ghcr.io/${{ github.repository }}:${{ github.ref_name }}'
      GHCR_IMAGE: '${{ github.repository }}:${{ github.ref_name }}'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build, Tag and Push Image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build --build-arg -f Dockerfile -t ${GHCR_FULL_NAME} -t ghcr.io/${{ github.repository }}:latest .
          docker push ${GHCR_FULL_NAME}
          docker push ghcr.io/${{ github.repository }}:latest
